apiVersion: "extensions/v1beta1"
kind: "ReplicaSet"
metadata:
  finalizers: []
  labels:
    app: "openshifttest3"
    cluster: "openshifttest3-test"
    openshifttest3-test-v000: "true"
    replication-controller: "openshifttest3-test-v000"
    stack: "test"
    version: "0"
  name: "openshifttest3-test-v000"
  namespace: "default"
  ownerReferences: []
spec:
  replicas: 1
  selector:
    matchExpressions: []
    matchLabels:
      app: "openshifttest3"
      cluster: "openshifttest3-test"
      openshifttest3-test-v000: "true"
      replication-controller: "openshifttest3-test-v000"
      stack: "test"
      version: "0"
  template:
    metadata:
      finalizers: []
      labels:
        app: "openshifttest3"
        cluster: "openshifttest3-test"
        openshifttest3-test-v000: "true"
        replication-controller: "openshifttest3-test-v000"
        stack: "test"
        version: "0"
      ownerReferences: []
    spec:
      containers:
      - args: []
        command: []
        env: []
        image: "quay.io/veerendra2/restapp:119"
        imagePullPolicy: "Always"
        name: "veerendra2-restapp"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        - containerPort: 9090
          name: "monitor"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders: []
            path: "/greeting"
            port: 8080
            scheme: "HTTP"
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        volumeMounts: []
        terminationMessagePolicy: "File"
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "my-docker-registry"
      restartPolicy: "Always"
      securityContext:
        supplementalGroups: []
      terminationGracePeriodSeconds: 30
      volumes: []
      schedulerName: "default-scheduler"
status:
  availableReplicas: 1
  conditions: []
  fullyLabeledReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
